🐛 Fixed more DPI stuff in the monitor moving scripts

diff --git a/scripts/make_two_screens b/scripts/make_two_screens
--- a/scripts/make_two_screens
+++ b/scripts/make_two_screens
@@ -1,8 +1,17 @@
-#!/bin/sh
+#!/bin/bash
 
 DP1=$(xrandr | grep -E 'DP-([0-9])-1 connected' | cut -d' ' -f1)
 DP2=$(xrandr | grep -E 'DP-([0-9])-2 connected' | cut -d' ' -f1)
 
-xrandr --dpi 156 --output eDP-1 --off \
+DPI=${1:-96}
+
+if [ "$DP1" = "" ] || [ "$DP2" = "" ]
+then
+  echo "Failed to detect screens: DP1=\"$DP1\", DP2=\"$DP2\""
+  exit 1
+fi
+
+xrandr --dpi "$DPI" --output eDP-1 --off \
   --output "$DP2" --pos 0x0 --mode 1920x1080 --rate 75 \
   --output "$DP1" --pos 1920x0 --mode 1920x1080 --rate 75 --primary
+echo "Xft.dpi: $DPI" | xrdb -merge
